### ISSUE TITLE
[FE] Rename and Reorganise files and folders structure

### ISSUE THREAD

**Issue by jordimorillo** [IT-Academy-BCN/ita-profiles#266]

**Comment by JuanDNJ** [comment]
Cual seria la mejor, organización?
![Image](https://github.com/user-attachments/assets/79177aca-443a-4c65-83fe-b79aca12fc27)

**Comment by JuanDNJ** [comment]
### [FE] Refactoring: api folder "src/api"

- [ ]  Filled

#### Who wants to work on this task?

---

- [ ] Juan

**Comment by JuanDNJ** [comment]
Se podría refactorizar la carpeta api "src/store"

He creado un ejemplo de como podría quedar?
Está claro que se puede mejorar, las ideas o comentarios, son bienvenidos jjajaja

Link de [excalidraw](https://excalidraw.com/#json=VSz5osqOZWv9Bm0cSrJQQ,B-Bp7MASCAHwsK9s_pkokA) para verlo o editarlo.

![Image](https://github.com/user-attachments/assets/66425e05-025a-4024-a0d7-36232cb1341e)

**Comment by JuanDNJ** [comment]
# Refactoring tasks

### [FE] Refactoring: "src/store"

- [ ]  Filled

#### Who wants to work on this task?

---

- [ ] Juan
- [ ] Aida
- [ ] Tomas

**Comment by JuanDNJ** [comment]
***Se podría refactorizar la carpeta api "src/assets"***

He creado un ejemplo de como podría quedar?
Está claro que se puede mejorar, las ideas o comentarios, son bienvenidos jjajaja

Link de [excalidraw](https://excalidraw.com/#json=VLRC79RXtdxvNGJURNNdy,sFc_vwFmfq3zj-cw1d6a2A) para verlo o editarlo.

![Image](https://github.com/user-attachments/assets/88f7eaa2-df55-4a40-aebe-11deabd34cd5)
